### ISSUE TITLE
No links in pypi 

### ISSUE THREAD

**Issue by wardcraigj** [phareous/insteonlocal#1]
Hey,
re: https://github.com/home-assistant/home-assistant/issues/3811
I'm getting started on trying to integrate this with HomeAssistant and https://pypi.python.org/simple/insteonlocal/ seems to be empty resulting in an error when trying to pip install or include in requirements.txt.

I was able to install it by `pip install git+https://github.com/phareous/insteonlocal.git` but unfortunately the requirements parser seems to barf on that, so I can't really include it properly.

In the issue on the hass project you had mentioned are a PHP developer by trade. I work as a PHP dev too and this is the first real python project I'm trying to dig my teeth into, so unfortunately I don't have any experience with pip and can't offer any quick fixes.

**Comment by wardcraigj** [comment]
I was able to include this as a requirement by adding as follows: `git+https://github.com/phareous/insteonlocal.git#insteonlocal==0.1`

I can start working on the homeassistant side. I can close this issue since this workaround meets my needs for now, though you might need to tag a version on the repo that we can pin this too

**Comment by phareous** [comment]
I just uploaded a new package 0.21...I'm hoping it works as I did a few more steps this time and made sure to tag it, etc. Also this new package has the latest code which has better buffer reading, etc.

**Comment by wardcraigj** [comment]
Oh great! Thanks! Looks like I can pull that package, but I can't install it without elevating. it looks like it's trying to put the .json files in another directory. Might need to change something in the manifest?

these are the files pip is trying to create:
```
  /usr/local/device_categories.json
  /usr/local/device_models.json
  /usr/local/lib/python3.5/site-packages/__pycache__/insteonlocal.cpython-35.pyc
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.1-py3.5.egg-info
  /usr/local/lib/python3.5/site-packages/insteonlocal.py
```

**Comment by phareous** [comment]
Ok I redid it - update the package and try again

**Comment by wardcraigj** [comment]
Awesome. Installed without elevation!

It looks like now insteonlocal.py doesn't end up in the right directory making the path referencing the json files incorrect

```
  /usr/local/lib/python3.5/site-packages/__pycache__/insteonlocal.cpython-35.pyc
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/INSTALLER
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/METADATA
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/RECORD
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/WHEEL
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/metadata.json
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.22.dist-info/top_level.txt
  /usr/local/lib/python3.5/site-packages/insteonlocal.py
```

**Comment by phareous** [comment]
Where did the device_models.json file install to? What error does it give when you try to run the example (assuming you customized the hub info)

**Comment by wardcraigj** [comment]
Actually, looking at that again, it doesn't look like they did install.

The error that I get is: `[Errno 2] No such file or directory: '/usr/local/lib/python3.5/site-packages/data/device_categories.json'`

**Comment by phareous** [comment]
Ok try again

**Comment by wardcraigj** [comment]
Hmm, still the same error on 0.24.`[Errno 2] No such file or directory: '/usr/local/lib/python3.5/site-packages/data/device_categories.json'`

 I wonder if there is an option I have to set when I pull it down?

```
  /usr/local/lib/python3.5/site-packages/__pycache__/insteonlocal.cpython-35.pyc
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/INSTALLER
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/METADATA
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/RECORD
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/WHEEL
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/metadata.json
  /usr/local/lib/python3.5/site-packages/insteonlocal-0.24.dist-info/top_level.txt
  /usr/local/lib/python3.5/site-packages/insteonlocal.py
```

**Comment by phareous** [comment]
Ok try again. Python packaging definitely isn't straightforward..and unfortunately I can't easily test since I only have one python computer at the moment

**Comment by wardcraigj** [comment]
Sorry, I'm not very familiar with Python packaging either, I wish I could be of more help. Here's the output:

```
$ pip install insteonlocal
Collecting insteonlocal
Installing collected packages: insteonlocal
Successfully installed insteonlocal-0.26
```

```
$ pip show -f insteonlocal
Name: insteonlocal
Version: 0.26
Summary: InsteonLocal allows local (non-cloud) control of the Insteon Hub 2245-222
Home-page: https://github.com/phareous/insteonlocal
Author: Michael Long
Author-email: mplong@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.5/site-packages
Requires:
Files:
  __pycache__/insteonlocal.cpython-35.pyc
  insteonlocal-0.26.dist-info/DESCRIPTION.rst
  insteonlocal-0.26.dist-info/INSTALLER
  insteonlocal-0.26.dist-info/METADATA
  insteonlocal-0.26.dist-info/RECORD
  insteonlocal-0.26.dist-info/WHEEL
  insteonlocal-0.26.dist-info/metadata.json
  insteonlocal-0.26.dist-info/top_level.txt
  insteonlocal.py
```

**Comment by phareous** [comment]
ok try again (0.27)

**Comment by wardcraigj** [comment]
I'll try pulling this down as soon as I get in. Unfortunately my hub bricked somehow over the weekend and my replacement won't be in until tomorrow, so I won't be able to do much else until then, but I should still be able to tell if the package is coming down right

**Comment by wardcraigj** [comment]
Looks like I'm still not seeing the .json files coming down. No rush on a fix just for me. Like I said, my hub isn't even functional right now, and when my replacement arrives, I can just pull the .json files directly from this git repo and add them manually so that I can get working on this. I'm also getting married in less than two weeks, so I probably won't have a ton of time to dig into this anyhow

**Comment by phareous** [comment]
OK i finally have it. I did some virtualenvs on my machine and kept working at it until it worked. I now have it broken up into different files as well (Hub, Switch, Dimmer, Group). Python doesn't do classes like PHP so technically each of these files is a module inside of a package, and each module has just one class. So we end up with Hub.Hub, Switch.Switch. Dimmer.Dimmer, Group.Group. I don't like the redundancy but it lets me have each in their own file. And technically could add other stuff in the future like Dimmer.Utilities or  whatever. Could change it to be Light.Switch, Light.Dimmer, etc.

Anyways I might eventually look at the HASS stuff too and if you'd like to collaborate we could setup a shared git. I don't really have a ton of time right now either (we're building a new house and selling the current one). Best wishes for your marriage and let me know when you start coding again 

Here is what I did to test:
mkdir /temp/insteontest
cd /temp/insteontest
virtualenv -p /usr/bin/python3 py3env
source py3env/bin/activate
pip install insteonlocal
pip install requests
created example.py (see github)
created config.py (see the dist/example on github)
ran example.py

**Comment by wardcraigj** [comment]
Thanks so much for the well wishes! I hope everything goes well with your build and sale as well!

I had a little bit of time to work on the HASS side of this today, and I managed to get Home Assistant to get Home assistant loading the library in the components/platform on boot. The library works great when I defined devices in the config, and the class that I use it in seems to be working when I address it in the setup method, but for some reason the devices aren't getting added after being set-up.

If you are wanting to take a look or pick at it, I forked the main HASS repo and have been working there. Here's the diff https://github.com/home-assistant/home-assistant/compare/dev...wardcraigj:insteon-local

I'll probably bump that insteon discussion on the main repo to update on progress and mention the issue I'm running into with devices because I'm sure the solution is probably painfully obvious to someone more familiar with the project. I doubt I'll have too much time to work on this in the next two weeks, but we'll see.

**Comment by camrun91** [comment]
I would be more than happy to help with this in any way that I can I have Home assistant running now and have Insteon working as a custom component plugged through openhab.  I may take a look at this in the next few days.

**Comment by phareous** [comment]
Thanks camrun91 I could use any help you can give. I am sure there are lots of cases where the library fails and needs tweaking (especially with the buffer status), and Craig may need help fleshing out the HA integration. Once it is all working then I want to start looking into:
1. Group/scenes
2. Getting status from the switches (so to know if someone manually triggers a switch or scene, or uses the insteon app)
3. Adding more device types like receptacles, motion sensors, thermostats, etc.

**Comment by camrun91** [comment]
So your fork of Homeassistant would just need to be installed inplace of the one that is currently installed right?

**Comment by wardcraigj** [comment]
yep, should be good to go. The one thing I'm not entirely sure about working is whether the Hub object in the local library needs to pass in the device Id to get status when we update, if so, it should be a simple change there (see issue 2). I was also seeing, in some cases, HASS trying to add lights before the platform had been configured/hub object initialized. I think someone on the HASS insteon_hub issue was possibly going to take a look at that at some point

**Comment by phareous** [comment]
Passing the device id in would attempt to find that device in the buffer and report back the status. It might not be absolutely necessary for just turning stuff on/off...you just need to check it to be 100% ensured the command worked. I think with dual band it should probably always work but if the network is flooded with traffic or if its single band I guess the device could miss the command. Also if someone's device was malfunctioning. It would just be a matter of how exact and reliable we want this to be. When we get to scenes/groups we'll probably need to ignore the status as you'll be getting a flood of responses from every device in the scene.

**Comment by wardcraigj** [comment]
I think the issue is that I'm looking for a specific device status by calling status() on an instantiated Dimmer object but the status isn't being returned since it calls hub.getDeviceStatus which doesn't pass the deviceId into getBufferStatus

**Comment by phareous** [comment]
So actually calling device.status makes a direct call to the device (command 19) and then checks the buffer for the response. You probably don't want to do that. Instead check the return code from the .on or .off, etc. command. It is internally calling checkSuccess which will search the buffer for that device.

Also I was looking over the code..I don't think you need to call discovery.load_platform, but just call load_platform. I don't think we need the discovery service as it will never find a new device since the devices are static in the user's config, and not discoverable.

See (assuming documentation is up-to-date):

https://home-assistant.io/developers/component_generic_discovery/
and
https://home-assistant.io/developers/component_discovery/

**Comment by phareous** [comment]
This might also be helpful

https://home-assistant.io/developers/platform_example_light/

**Comment by wardcraigj** [comment]
Ah! Thanks, yeah, you are right about discovery service.

Yeah, updating on success after an action isn't an issue so much as the fact that HASS seems to poll the entities update function to stay up to date with any changes that might have occured externally, so update needs to have something to hit to check the device state

**Comment by phareous** [comment]
Ultimately what would be good (but maybe complicated) is for you to keep track of state (I assume HASS has this built-in), using the response when you run the command. Then have another loop that runs every 5 minutes or something that actually queries the devices. The issue is its going to be slow to query each device individually, and it generates a lot of insteon network traffic. This obviously doesn't scale well...imagine doing this for 50, or 100 devices...

**Comment by camrun91** [comment]
Ok am I missing somewhere that you have said what needs to be added to the config for the HASS part to work? I am commenting out the current insteon stuff I have set up to test this.

**Comment by wardcraigj** [comment]
@phareous Yep, agreed. I haven't looked into how to throttle the polling frequency, but I assume hass has a method for doing that. Ideally, I'd like to set a default for the polling frequency and have it configurable by the user between a set floor and ceiling.

@camrun91 - it should be a comment in light/insteon_local, but this is what it should look like

```yaml
insteon_local:
  host: YOUR HUB IP
  username: YOUR HUB USERNAME
  password: YOUR HUB PASSWORD

light:
  - platform: insteon_local
    lights:
      dining_room:
        device_id: 30DA8A
        name: Dining Room
      living_room:
        device_id: 30D927
        name: Living Room
```

**Comment by camrun91** [comment]
So did you remove the . in the device ID? all of mine have a . every 2 characters
so it looks like 30.DA.8A

**Comment by phareous** [comment]
Yes there is no need for periods or colons in the address

**Comment by camrun91** [comment]
OK cool I think I have this working for the most part.

**Comment by camrun91** [comment]
OK so I assume we do not have the switches ability built in yet as I do not see the code anywhere?
I have the lights working I think. I have two dimmer modules that seem to be working. I also have two switches that I am trying to set up but it does not look like the switch component is set up in Homeassistant yet.

**Comment by wardcraigj** [comment]
Yeah, just dimmers right now

**Comment by wardcraigj** [comment]
The library does support switches, so it will be an easy add, though

**Comment by camrun91** [comment]
Ok I have them showing up but I am getting odd text in HASS `INFO:insteonlocal.Hub:directCommand: Device: 2F2A84 Command: 19 Command 2: 00 MsgType: Standard
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/3?02622F2A840F1900=I=3
INFO:insteonlocal.Hub:getBufferStatus: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getDirectCommand: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getBufferStatus: Got raw text with size 35 and contents: 401 Unauthorized: Password required
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/1?XB=M=1
INFO:insteonlocal.Hub:clearBuffer: <Response [401]>
OrderedDict([('error', False),
             ('success', True),
             ('message', ''),
             ('msgs',
              [OrderedDict([('im_code', '1 ')]),
               OrderedDict([('im_code', 'au')]),
               OrderedDict([('im_code', 'or')]),
               OrderedDict([('im_code', 'ed')]),
               OrderedDict([('im_code', 'Pa')]),
               OrderedDict([('im_code', 'wo')]),
               OrderedDict([('im_code', ' r')]),
               OrderedDict([('im_code', 'ui')])])])
INFO:insteonlocal.Hub:
Dimmer 2F2A84 status: None
INFO:insteonlocal.Hub:
getDeviceStatus for device 2F25FD
INFO:insteonlocal.Hub:directCommand: Device: 2F25FD Command: 19 Command 2: 00 MsgType: Standard
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/3?02622F25FD0F1900=I=3
INFO:insteonlocal.Hub:getBufferStatus: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getDirectCommand: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getBufferStatus: Got raw text with size 35 and contents: 401 Unauthorized: Password required
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/1?XB=M=1
INFO:insteonlocal.Hub:clearBuffer: <Response [401]>
OrderedDict([('error', False),
             ('success', True),
             ('message', ''),
             ('msgs',
              [OrderedDict([('im_code', '1 ')]),
               OrderedDict([('im_code', 'au')]),
               OrderedDict([('im_code', 'or')]),
               OrderedDict([('im_code', 'ed')]),
               OrderedDict([('im_code', 'Pa')]),
               OrderedDict([('im_code', 'wo')]),
               OrderedDict([('im_code', ' r')]),
               OrderedDict([('im_code', 'ui')])])])
INFO:insteonlocal.Hub:
Dimmer 2F25FD status: None`

**Comment by camrun91** [comment]
Ok lets see if I can get this to show right. I am getting this in HASS cli 
`INFO:insteonlocal.Hub:directCommand: Device: 2F2A84 Command: 19 Command 2: 00 MsgType: Standard
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/3?02622F2A840F1900=I=3
INFO:insteonlocal.Hub:getBufferStatus: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getDirectCommand: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getBufferStatus: Got raw text with size 35 and contents: 401 Unauthorized: Password required
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/1?XB=M=1
INFO:insteonlocal.Hub:clearBuffer: <Response [401]>
OrderedDict([('error', False),
             ('success', True),
             ('message', ''),
             ('msgs',
              [OrderedDict([('im_code', '1 ')]),
               OrderedDict([('im_code', 'au')]),
               OrderedDict([('im_code', 'or')]),
               OrderedDict([('im_code', 'ed')]),
               OrderedDict([('im_code', 'Pa')]),
               OrderedDict([('im_code', 'wo')]),
               OrderedDict([('im_code', ' r')]),
               OrderedDict([('im_code', 'ui')])])])
INFO:insteonlocal.Hub:
Dimmer 2F2A84 status: None
INFO:insteonlocal.Hub:
getDeviceStatus for device 2F25FD
INFO:insteonlocal.Hub:directCommand: Device: 2F25FD Command: 19 Command 2: 00 MsgType: Standard
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/3?02622F25FD0F1900=I=3
INFO:insteonlocal.Hub:getBufferStatus: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getDirectCommand: http://192.168.1.2:25105/buffstatus.xml
INFO:insteonlocal.Hub:getBufferStatus: Got raw text with size 35 and contents: 401 Unauthorized: Password required
INFO:insteonlocal.Hub:postDirectCommand: http://192.168.1.2:25105/1?XB=M=1
INFO:insteonlocal.Hub:clearBuffer: <Response [401]>
OrderedDict([('error', False),
             ('success', True),
             ('message', ''),
             ('msgs',
              [OrderedDict([('im_code', '1 ')]),
               OrderedDict([('im_code', 'au')]),
               OrderedDict([('im_code', 'or')]),
               OrderedDict([('im_code', 'ed')]),
               OrderedDict([('im_code', 'Pa')]),
               OrderedDict([('im_code', 'wo')]),
               OrderedDict([('im_code', ' r')]),
               OrderedDict([('im_code', 'ui')])])])
INFO:insteonlocal.Hub:
Dimmer 2F25FD status: None`

**Comment by phareous** [comment]
Check the pass for your hub

401 Unauthorized: Password required

**Comment by wardcraigj** [comment]
Looks like an http auth issue. If you hit this url and auth with the password from your config, do you see anything? http://192.168.1.2:25105/1?XB=M=1

**Comment by wardcraigj** [comment]
the user and pass is different from what you use to log into the app, you can set/change it within the app in the hub/house settings

**Comment by phareous** [comment]
I probably need to add a check to the library for HTTP status code

**Comment by camrun91** [comment]
Isn't the user and pass what is on the bottom of the hub?

**Comment by phareous** [comment]
It is initially, but can be changed in the insteon app. Also double check your IP and make sure you're hitting the hub and not some other device

**Comment by camrun91** [comment]
OK I probably typed the pass word wrong as it was working this morning going through openhab

**Comment by camrun91** [comment]
haha oops missed a letter in the pass everything is working now

**Comment by camrun91** [comment]
even just turned the light on with HASS webfront and off with the insteon and app HASS refelected the change pretty quickly.

**Comment by camrun91** [comment]
Ok one more question what is up with this segment in the CLI?
`INFO:insteonlocal.Hub:clearBuffer: <Response [200]>
OrderedDict([('error', False),
             ('success', True),
             ('message', ''),
             ('msgs',
              [OrderedDict([('im_code', '62'),
                            ('im_code_desc', 'Send Message'),
                            ('raw', '02622F2A840F190006'),
                            ('id', '2F2A84'),
                            ('flags', '0F'),
                            ('cmd1', '19'),
                            ('cmd2', '00'),
                            ('ack_or_nak', '06')]),
               OrderedDict([('im_code', '50'),
                            ('im_code_desc', 'Standard Message Received'),
                            ('raw', '02502F2A843924192F0000'),
                            ('id_from', '2F2A84'),
                            ('id_high', '39'),
                            ('id_mid', '24'),
                            ('id_low', '19'),
                            ('flag1', '2'),
                            ('flag2', 'F'),
                            ('cmd1', '00'),
                            ('cmd2', '00')])])])
INFO:insteonlocal.Hub:`

**Comment by phareous** [comment]
This log is just a breakdown of two commands

02622F2A840F190006
0262 - hub sent command
2F2A84 - to this device
0F - flags
19 - this is the "status" request command
00 - no arguments for status command
06 - this is an ack

02502F2A843924192F0000
0250 - received to hub from device
2F2A84 - from this device
392419 - to this device (hub)
2F - 2 means ack, F is the hop count
00 - database delta
00 - current on level (so its off)

**Comment by camrun91** [comment]
Ah OK so it looks like we are getting really close here. @wardcraigj if you want to add me as a contributor on the HASS part I will try when I get off work to get the Switch part working. Should be pretty straight forward and similar to the lights part.

**Comment by wardcraigj** [comment]
@camrun91, did you need to modify the insteonlocal library in order for the updates to work?

**Comment by camrun91** [comment]
I did not have too let me double check that they are working.

**Comment by camrun91** [comment]
How would you feel about opening a channel on glitter chat for this. I synced my Github desktop today and merged the dev branch with the changes you have made. I am hoping tomorrow I can do some research into HASS API as this will be the first time I am coding for HASS and am not failure at all with the API or anything.

**Comment by camrun91** [comment]
I have not looked through all the code yet but if one big hurdle we are facing is the fact that the hub is not passing state changes by physical push or app toggles I think there is a way to poll the hub to get status of each device. This could be a start to get us going and something to improve on in future.

**Comment by phareous** [comment]
It should be possible to query the hub buffer every second to get state changes without having to query the devices individually

**Comment by phareous** [comment]
I've never used glitter but we could give it a shot. I use slack for everything. Also we could do a thread on the Hass forum

**Comment by camrun91** [comment]
I use Slack as well lol that works fine with me. I just know that the official chat thing is glitter. I Just committed the changes to @wardcraigj HASS branch for insteon_local I think they should have switches working. I am going to test it out in the morning.

**Comment by wardcraigj** [comment]
Cool! I don't have any pure switches, so if you've tested and they seem to be working, then that's awesome! Also, if you have a chance to try making that change in the library Dimmer file (might need to make it in switch as well, though I'm not sure) and see if the state updates work, that would be great! I'm thinking we'll probably want status() to return something meaningful anyway, even if it's too cumbersome to be hitting with the frequency that HASS seems to wants to.

If we do make that change and everything seems to work, do you think we should create a PR to get the support in place before optimizing by creating a buffer supervisor within HASS to take care of maintaining state more efficiently?

I'm also down for either gitter or slack.

**Comment by camrun91** [comment]
I can create a slack channel for us to get into and we can let other people know they can go there for help developing. I am going to test the switches this morning then see if I can get the state changes working. 

I think doing a PR with the lights and switches working and status working for now will be good. I don't think we have to worry about overloading the Insteon network unless someone has a lot of devices.

**Comment by phareous** [comment]
Yeah I am fine with slack or glitter. I know glitter is their official one...I'd have to see what clients are out there. The nice thing about slack is I already have it on my phone, windows computer, linux computer, etc.

One thing I saw somewhere is they want tests, but I don't know how strict they are about that. I have no clue yet how to go about writing tests in python

And also documentation

And also make sure the code uses PEP8 style

I doubt I have to do much for the local library since its a third party module, but I will probably eventually try to make it adhere to all of that as good practice

Look over this:
https://home-assistant.io/developers/development_checklist/
https://home-assistant.io/developers/development_testing/

**Comment by camrun91** [comment]
OK slack channel is up and working should be able to join the domain hass-insteon.slack.com

**Comment by phareous** [comment]
I think you have to invite me, it won't let me just join. You can use mlong@mlong.us

**Comment by camrun91** [comment]
Ok you should have an invite I set it up to allow you to automatic sign up as well.

**Comment by camrun91** [comment]
https://hass-insteon.slack.com/signup That should allow you to sign up if anyone else wants to join
