### ISSUE TITLE
Dimmers flicker

### ISSUE THREAD

**Issue by isitmark** [phareous/insteonlocal#20]
Few weeks in to Home Assistant.. Loaded the insteon lights and switches. I have 16 lights/dimmers 7switches several firmware versions and types.
Hub 2245-222.

It seems the polling/checking states causes a lot of traffic. I have noticed when homeassistant is running several of my dimmers flicker randomly.So we'll see the lights turn off and on <1 second. When I turn off homeassistant/insteon config they no longer flicker. Is there a way to slow down how often it checks states?

Vanilla install..
Has anyone ran into this?

Thanks!

**Comment by phareous** [comment]
Hey this is for the insteon library, you'll probably need to submit this to Home Assistant, although there is only one developer dealing with insteon there and he has been off on other projects. 

https://github.com/home-assistant/home-assistant/issues

But to answer your question, there is a scan_interval setting in the home assistant config...you can try playing around with that setting and see if it makes a difference

https://home-assistant.io/docs/configuration/platform_options/
